### ISSUE TITLE
Disable error dialog boxes.

### ISSUE THREAD

**Issue by wlsouza** [haseeb-heaven/GTLibPy#2]
Is there a way to disable the error dialog boxes?
I want to do something like that: 
![image](https://user-images.githubusercontent.com/41215437/95021889-27340800-064a-11eb-9e3d-4dadd6efcf65.png)
Unfortunately with the dialog box active I cannot run the trainer until the game is open ...

**Comment by haseeb-heaven** [comment]
No right now there is no way to suppress errors in library in future i will add them .
And don't use this for online games .
Thanks

**Comment by wlsouza** [comment]
Thanks for the quick response!
Okay, Among Us is just a test to find the process. It's the only game I have installed, so I used it as an example.

**Comment by haseeb-heaven** [comment]
I have added them now. Support for Disabling Errors and Warnings
